[Eth]
NetworkId = 1
TrieTimeout = 4000000000000
TriesInMemory = 156

[Eth.Verifier]
ConcurrencyLimit = 64
ConfusedDiffLayers = 15
WaitConfirmedSecondsLimit = 10
ClearIgnoreRounds = 0

[Eth.Verifier.Redis]
ClusterAddr = ["tf-nodereal-prod-rpcplanteth.uzn8om.clustercfg.use1.cache.amazonaws.com:6379"]
PoolTimeout = "10s"
DialTimeout = "10s"
WriteTimeout = "5s"
ReadTimeout = "10s"

[Node]
DataDir = "/server/verifier/data"
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]

[Node.LogConfig]
FileRoot = "/server/verifier/logs/"
FilePath = "verifier.log"
MaxBytesSize = 10485760
Level = "info"
