[Eth]
NetworkId = 1
TrieTimeout = 4000000000000
TriesInMemory = 150

[Eth.Publisher]
PublishTimeout = "30s"
MaxAddedBlocks = 513
ExpireTime = "6h"
HealthTimeout = "30s"
DiscoveryTTL = "20s"
DiscoveryRenew = "3s"
BackupLimit = 10000

[Eth.Publisher.Redis]
Namespace = "rpcplanteth"
ClusterAddr = ["tf-nodereal-prod-rpcplanteth.uzn8om.clustercfg.use1.cache.amazonaws.com:6379"]
PoolTimeout = "10s"
DialTimeout = "10s"
WriteTimeout = "1m"
ReadTimeout = "15s"

[Node]
DataDir = "/server/publisher/data"
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]

[Node.LogConfig]
FileRoot = "/server/publisher/logs/"
FilePath = "publisher.log"
MaxBytesSize = 10485760
Level = "info"
